# kind: DatadogAgent
# apiVersion: datadoghq.com/v2alpha1
# metadata:
#   name: datadog
# spec:
#   global:
#     site: "us5.datadoghq.com"
#     clusterName: "home_k8s"
#     kubelet:
#       tlsVerify: false
#     credentials:
#       apiSecret:
#         secretName: datadog-secret
#         keyName: api-key
#       appSecret:
#         secretName: datadog-secret
#         keyName: app-key
#   features:
#     logCollection:
#       enabled: true
#       containerCollectAll: true
#     kubeStateMetricsCore:
#       enabled: true
#   override:
#     clusterAgent:
#       image:
#         name: gcr.io/datadoghq/cluster-agent:latest
#     nodeAgent:
#       image:
#         name: gcr.io/datadoghq/agent:latest
#       extraConfd:
#         configMap:
#           name: datadog-checks
#       containers:
#         agent:
#           volumeMounts:
#             - name: etcd-certs
#               readOnly: true
#               mountPath: /host/etc/kubernetes/pki/etcd
#             - name: disable-etcd-autoconf
#               mountPath: /etc/datadog-agent/conf.d/etcd.d
#             - name: disable-scheduler-autoconf
#               mountPath: /etc/datadog-agent/conf.d/kube_scheduler.d
#             - name: disable-controller-manager-autoconf
#               mountPath: /etc/datadog-agent/conf.d/kube_controller_manager.d
#       volumes:
#         - name: etcd-certs
#           hostPath:
#             path: /etc/kubernetes/pki/etcd
#         - name: disable-etcd-autoconf
#           emptyDir: {}
#         - name: disable-scheduler-autoconf
#           emptyDir: {}
#         - name: disable-controller-manager-autoconf
#           emptyDir: {}
#       tolerations:
#         - key: node-role.kubernetes.io/control-plane
#           operator: Exists
#           effect: NoSchedule
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: datadog-checks
# data:
#   etcd.yaml: |-
#     ad_identifiers:
#       - etcd
#     init_config:
#     instances:
#       - prometheus_url: https://%%host%%:2379/metrics
#         tls_ca_cert: /host/etc/kubernetes/pki/etcd/ca.crt
#         tls_cert: /host/etc/kubernetes/pki/etcd/server.crt
#         tls_private_key: /host/etc/kubernetes/pki/etcd/server.key
#   kube_scheduler.yaml: |-
#     ad_identifiers:
#       - kube-scheduler
#     instances:
#       - prometheus_url: https://%%host%%:10259/metrics
#         ssl_verify: false
#         bearer_token_auth: true
#   kube_controller_manager.yaml: |-
#     ad_identifiers:
#       - kube-controller-manager
#     instances:
#       - prometheus_url: https://%%host%%:10257/metrics
#         ssl_verify: false
#         bearer_token_auth: true
