# manifest for simple deployment.
kind: Deployment
apiVersion: apps/v1
metadata:
  name: log-service
  labels:
    app: log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-service
  template:
    metadata:
      labels:
        app: log-service
    spec:
      containers:
        - name: log-service
          image: ysfm/log_service:0.0.2
          env:
            - name: EXAMPLE_VAR
              value: "normal log service"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: credential-log-service
  labels:
    app: credential-log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credential-log-service
  template:
    metadata:
      labels:
        app: credential-log-service
    spec:
      containers:
        - name: credential-log-service
          image: ysfm/log_service:0.0.2
          env:
            - name: EXAMPLE_VAR
              value: "credential log service"
