kubeProxyReplacement: strict 
k8sServiceHost: 192.168.0.100 
k8sServicePort: 6443 
prometheus:
  enabled: true 
operator:
  prometheus:
    enabled: true 
cluster:
  id: 0
  name: home-k8s
encryption:
  nodeEncryption: false
hubble:
  enabled: true
  metrics:
    enableOpenMetrics: true
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction