- name: Initialize the cluster and save the join command
  hosts: master
  become: true
  become_user: root
  tasks:
    - name: Check if kubeconfig exists
      ansible.builtin.stat:
        path: /etc/kubernetes/admin.conf
      register: kubeconfig

    - name: Copy kubadm config
      ansible.builtin.template:
        src: ../settings/kubeadm-config.yaml.tpl
        dest: /tmp/kubeadm-config.yaml
        mode: "0644"

    - name: Initialize the cluster
      ansible.builtin.command: "kubeadm init --config /tmp/kubeadm-config.yaml"
      args:
        creates: /etc/kubernetes/admin.conf
      when: not kubeconfig.stat.exists

    - name: Setup kubectl config
      when: not kubeconfig.stat.exists
      block:
        - name: Create .kube directory
          ansible.builtin.command: "mkdir -p $HOME/.kube"
          become: true
          become_user: "{{ ansible_user }}"
          changed_when: false
        - name: Copy kubeconfig
          ansible.builtin.command: "{{ item }}"
          with_items:
            - "cp -f /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config"
            - "chown {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.kube/config"
          become: true
          become_user: "root"
          changed_when: true

    - name: Get join command
      ansible.builtin.command: kubeadm token create --print-join-command
      become: true
      become_user: "{{ ansible_user }}"
      register: join_command
      changed_when: true

    - name: Save join command to a file
      ansible.builtin.copy:
        content: "{{ join_command.stdout }}"
        dest: /join-command
        mode: "0644"
