- name: Initialize the cluster and save the join command
  hosts: master
  become: true
  become_user: root
  tasks:
    - name: Check if kubeconfig exists
      ansible.builtin.stat:
        path: /etc/kubernetes/admin.conf
      register: kubeconfig

    - name: Initialize the cluster
      ansible.builtin.command: "kubeadm init --apiserver-advertise-address={{ ansible_host }} --pod-network-cidr=192.168.0.0/16"
      args:
        creates: /etc/kubernetes/admin.conf
      when: not kubeconfig.stat.exists

    - name: Setup kubectl config
      ansible.builtin.command: "{{ item }}"
      with_items:
        - mkdir -p $HOME/.kube
        - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        - sudo chown $(id -u):$(id -g) $HOME/.kube/config
      changed_when: true
      when: not kubeconfig.stat.exists

    - name: Get join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command
      changed_when: true

    - name: Save join command to a file
      ansible.builtin.copy:
        content: "{{ join_command.stdout }}"
        dest: /join-command
        mode: "0644"
