- name: Install helm and cilium cli
  hosts: master
  vars:
    cli_arch: "amd64"
  tasks:
    - name: Install helm
      community.general.snap:
        name: helm
        classic: true

    - name: Get the architecture of the machine
      ansible.builtin.command: uname -m
      register: machine_arch
      changed_when: false

    - name: Set variable cli_arch to arm64 if machine architecture is aarch64
      ansible.builtin.set_fact:
        cli_arch: "arm64"
      when: machine_arch.stdout == 'aarch64'

    - name: Get cilium cli version
      ansible.builtin.uri:
        url: https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt
        return_content: true
      register: cilium_cli_version

    - name: Download cilium cli
      ansible.builtin.get_url:
        url: https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version.content }}/cilium-linux-{{ cli_arch }}.tar.gz
        dest: /tmp/cilium-linux-{{ cli_arch }}.tar.gz
        mode: "0644"
        checksum: sha256:/tmp/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum

    - name: Extract cilium cli
      ansible.builtin.unarchive:
        src: /tmp/cilium-linux-{{ cli_arch }}.tar.gz
        dest: /usr/local/bin
        remote_src: true

    - name: Remove downloaded cilium cli files
      ansible.builtin.file:
        path: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz"
        state: absent
