- name: Join the cluster
  hosts: all
  tasks:
    - name: Check if the worker has already joined the cluster
      ansible.builtin.shell: |
        set -o pipefail
        kubectl get nodes | grep {{ inventory_hostname }} || true
      args:
        executable: /bin/bash
      register: node_status
      delegate_to: "{{ hostvars[master_name].ansible_host }}"
      changed_when: false

    - name: Join the cluster
      when: node_status.stdout == ""
      block:
        - name: Fetch join command from master
          ansible.builtin.slurp:
            src: /join-command
          register: join_command
          delegate_to: "{{ hostvars[master_name].ansible_host }}"

        - name: Join the cluster
          ansible.builtin.command: "{{ join_command['content'] | b64decode }}"
          register: join_result
          become: true
          become_user: root
          changed_when: true
